@url = http://localhost:1323

###   GET /
GET {{url}}/
Content-Type: application/json

###   POST /users
POST {{url}}/users/create
Content-Type: application/json

{
    "name": "James",
    "email": "james@gmail.com",
    "address": {
        "city": "London",
        "street": "United Kingdom",
        "zip": "00834"
    }
}

